tasks:
- init: |
    sudo apt -y install cmake
    cmake -S. -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    cmake --build build --target all 
    sudo apt-get -y install libomp-dev
    sudo apt-get -y install libopenmpi-dev
    sudo apt-get install openmpi-bin
  command: |
    export OMP_NUM_THREADS=8
    gcc -o test -fopenmp main.c
    ./test
vscode:
  extensions:
    - twxs.cmake
    - franneck94.c-cpp-runner
    - webfreak.debug
